<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * DairyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DairyRepository extends \Doctrine\ORM\EntityRepository
{
}
