<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * FatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FatRepository extends \Doctrine\ORM\EntityRepository
{
}
