<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * FoodCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
