<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * FruitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FruitsRepository extends \Doctrine\ORM\EntityRepository
{
}
