<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * GrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrainRepository extends \Doctrine\ORM\EntityRepository
{
}
