<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * MealsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealsRepository extends \Doctrine\ORM\EntityRepository
{
}
