<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * SpicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpicesRepository extends \Doctrine\ORM\EntityRepository
{
}
