<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * SweetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SweetsRepository extends \Doctrine\ORM\EntityRepository
{
}
