<?php

namespace AppBundle\Repository\FoodCategories;

/**
 * VegetablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VegetablesRepository extends \Doctrine\ORM\EntityRepository
{
}
