<?php

namespace AppBundle\Repository;

/**
 * CardioTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardioTrainingRepository extends \Doctrine\ORM\EntityRepository
{
}
