<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\UserFood;

/**
 * FoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodRepository extends \Doctrine\ORM\EntityRepository
{
	public function findProducts($name){
	return $this->getEntityManager()
		->createQuery(
			'SELECT e
			FROM AppBundle:Food e
			WHERE e.name LIKE :str'
		)
		->setParameter('str', '%'.$name.'%')
		->getResult();
	}
}
