<?php

namespace AppBundle\Repository;

/**
 * MyFoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyFoodRepository extends \Doctrine\ORM\EntityRepository
{
}
