<?php

namespace AppBundle\Repository;

/**
 * MyStrengthTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyStrengthTrainingRepository extends \Doctrine\ORM\EntityRepository
{
	public function findMyTrainings($userId)
	{
		return $this->getEntityManager()
		->createQuery(
			'SELECT m.id, m.name
			FROM AppBundle:MyStrengthTraining m
			WHERE m.userId = :userId
			ORDER BY m.id')
		->setParameter('userId', $userId)
		->getResult();
	}
}
