<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * MyStrengthTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyStrengthTrainingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyTrainings($userId)
    {
        return $this->getEntityManager()
        ->createQuery(
            'SELECT m.id, m.name
			FROM AppBundle:MyStrengthTraining m
			WHERE m.userId = :userId
			AND m.isActive = :active
			ORDER BY m.id'
        )
        ->setParameter('userId', $userId)
        ->setParameter('active', true)
        ->getResult();
    }

    public function findItemToDisActive(User $user, $id)
    {
        return $this->createQueryBuilder('u')
          ->where('u.userId = :user AND u.id = :id')
          ->setParameter('user', $user)
          ->setParameter('id', $id)
          ->getQuery()
          ->getOneOrNullResult();
    }
}
