<?php

namespace AppBundle\Repository;

/**
 * MyStrengthTrainingExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyStrengthTrainingExerciseRepository extends \Doctrine\ORM\EntityRepository
{
}
