<?php

namespace AppBundle\Repository;

/**
 * StrengthTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrengthTrainingRepository extends \Doctrine\ORM\EntityRepository
{
	public function findTraining($training)
	{
		return $this->find($training);
		if (!$training) {
			throw $this->createNotFoundException();
		}
	}
}
