<?php

namespace AppBundle\Repository;

/**
 * StrengthTrainingExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrengthTrainingExerciseRepository extends \Doctrine\ORM\EntityRepository
{
}
