<?php

namespace AppBundle\Repository;

/**
 * StrengthTrainingCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrengthTrainingCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
