<?php

namespace AppBundle\Repository;

/**
 * UserCardioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCardioRepository extends \Doctrine\ORM\EntityRepository
{
	public function loadUserCardios($pickedDate, $user)
	{
		return $this->createQueryBuilder('u')
			->where('u.date = :dateD AND u.userId = :uId')
			->setParameter('dateD', $pickedDate)
			->setParameter('uId', $user->getId())
			->getQuery()
			->getResult();;
	}
}
