<?php

namespace AppBundle\Repository;

/**
 * UserStrengthTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStrengthTrainingRepository extends \Doctrine\ORM\EntityRepository
{
}
