<?php

namespace AppBundle\Repository;

/**
 * UserCardioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCardioRepository extends \Doctrine\ORM\EntityRepository
{
}
