<?php

namespace AppBundle\Repository;

/**
 * UserDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDataRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDailyCalories(Int $userId)
	{
		return $this->createQueryBuilder('d')
			->select('d.calories')
			->where('d.userId = :id')
			->setParameter('id', $userId)
			->getQuery()
			->getSingleScalarResult();
	}
}
