<?php

namespace AppBundle\Repository;


/**
 * UserFoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFoodRepository extends \Doctrine\ORM\EntityRepository
{

}
