<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * UserStrengthExerciseCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStrengthExerciseCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
